server:
  port: 8080

spring:
  #  数据库配置信息
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://localhost:3306/blogs?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: zwbsdmpy
  #    静态资源路径
  resources:
    static-locations: classpath:/static

# mybatis配置信息
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.dao

