#必要字段！Swagger规范版本，必须填2.0，否则该YAML将不能用于Swagger其他组件
swagger: '2.0'
#必要字段！描述API接口信息的元数据
info:
  #接口标题
  title: 获取博客初始信息
  #接口文档的描述
  description: 获取博客初始信息
  #版本号
  version: 1.0.0
#Swagger会提供测试用例，host指定测试时的主机名，如果没有指定就是当前主机,可以指定端口．
host: 127.0.0.1:8080
#定义的api的前缀，必须已/开头,测试用例的主机则为:host＋bashPath
basePath: /rest
#指定调用接口的协议，必须是:"http", "https", "ws", "wss"．默认是http.-表示是个数组元素，即schemes接受一个数组参数
schemes:
  - http
  - https
#对应与http协议头request的Accept，调用者可接受类型,默认是*/*,定义的类型必须是http协议定义的 Mime Types,RestfulAPI一般定义成application/json
#这两个是对所有接口的全局设置，在细化的接口中是还可以对应这两个属性来覆盖全局属性
produces:
  - application/json
#必要字段!定义可有可操作的API
paths:
  /blogs/siderMenuList:
   #必要字段!定义HTTP操作方法，必须是http协议定义的方法
    get:
      #接口概要
      summary: 获取左侧菜单栏列表
      #接口描述
      description: '获取左侧菜单栏列表'
      #标签，方便快速过滤出User相关的接口
      tags:
        - blogs
      #返回值描述，必要自动
      responses:
        #返回的http状态码
        200:
          description: 发送成功
          #描述返回值
          schema:
            #返回值格式，可选的有array,integer,string,boolean
            type: object
            items:
              #引用在definitions下定义的Users
              $ref: '#/definitions/SiderMenuList'
        #执行出错的处理
        default:
          description: 操作异常,执行失败.返回信息描述错误详情
          schema:
            #值类型
            type: object
            #定义属性
            properties:
            #属性名
              message:
                #类型
                type: string
definitions:
  SiderMenuList:
    #值类型
    type: object
    #定义属性
    properties:
    #属性名
      id:
        #类型
        type: string
        #描述
        description: 用户的唯一id
      username:
        type: string
        description: 用户名
      alias:
        type: string
        description: 别名